CREATE TYPE userrole_enum AS ENUM ('buyer', 'seller', 'admin');
CREATE TYPE userstatus_enum AS ENUM ('active', 'disabled');
CREATE TYPE walletstatus_enum AS ENUM ('active', 'disabled');
CREATE TYPE merchantauditstatus_enum AS ENUM ('draft', 'pending', 'approved', 'rejected', 'suspended');
CREATE TYPE productstatus_enum AS ENUM ('draft', 'pending_review', 'online', 'offline', 'rejected');
CREATE TYPE orderstatus_enum AS ENUM ('WAIT_PAY', 'EXPIRED', 'PAID', 'SHIPPED', 'COMPLETED', 'CANCELLED', 'REFUND_PENDING', 'REFUNDED', 'DISPUTED');
CREATE TYPE paymentstatus_enum AS ENUM ('WAIT_PAY', 'PAID', 'CANCELLED', 'EXPIRED');
CREATE TYPE refundstatus_enum AS ENUM ('pending', 'approved', 'rejected', 'completed', 'disputed');
CREATE TYPE disputestatus_enum AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE reviewstatus_enum AS ENUM ('visible', 'hidden', 'pending');
CREATE TYPE ledgerdirection_enum AS ENUM ('in', 'out', 'freeze', 'unfreeze');
CREATE TYPE walletbiztype_enum AS ENUM ('recharge', 'order_pay', 'refund', 'seller_settlement', 'admin_adjust');
CREATE TYPE aimessagerole_enum AS ENUM ('user', 'assistant', 'system');




CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role userrole_enum NOT NULL,
    status userstatus_enum NOT NULL DEFAULT 'active'::userstatus_enum,
    nickname VARCHAR(64),
    avatar_url VARCHAR(512),
    phone VARCHAR(32),
    email VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_user_role_username UNIQUE (role, username),
    CONSTRAINT uq_user_role_phone UNIQUE (role, phone),
    CONSTRAINT uq_user_role_email UNIQUE (role, email)
);

CREATE INDEX ix_user_account_email ON user_account (email);
CREATE INDEX ix_user_account_phone ON user_account (phone);
CREATE INDEX ix_user_account_role ON user_account (role);
CREATE INDEX ix_user_account_status ON user_account (status);
CREATE INDEX ix_user_account_username ON user_account (username);



CREATE TABLE merchant_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    shop_name VARCHAR(128) NOT NULL,
    shop_logo_url VARCHAR(512),
    shop_description TEXT,
    contact_name VARCHAR(64) NOT NULL,
    contact_phone VARCHAR(32) NOT NULL,
    audit_material_text TEXT,
    audit_images_json JSON,
    audit_status merchantauditstatus_enum NOT NULL DEFAULT 'draft'::merchantauditstatus_enum,
    audit_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(user_id) REFERENCES user_account (id)
);

CREATE INDEX ix_merchant_profile_audit_status ON merchant_profile (audit_status);
CREATE INDEX ix_merchant_profile_shop_name ON merchant_profile (shop_name);
CREATE UNIQUE INDEX ix_merchant_profile_user_id ON merchant_profile (user_id);

CREATE TABLE address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    receiver_name VARCHAR(64) NOT NULL,
    receiver_phone VARCHAR(32) NOT NULL,
    province VARCHAR(64) NOT NULL,
    city VARCHAR(64) NOT NULL,
    district VARCHAR(64) NOT NULL,
    detail VARCHAR(255) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(user_id) REFERENCES user_account (id)
);

CREATE INDEX ix_address_user_id ON address (user_id);

CREATE TABLE product_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id BIGINT,
    name VARCHAR(64) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(parent_id) REFERENCES product_category (id)
);

CREATE INDEX ix_product_category_name ON product_category (name);
CREATE INDEX ix_product_category_parent_id ON product_category (parent_id);

CREATE TABLE product_spu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    merchant_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    description TEXT,
    origin_place VARCHAR(128),
    cover_image_url VARCHAR(512),
    review_reason TEXT,
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    status productstatus_enum NOT NULL DEFAULT 'draft'::productstatus_enum,
    deleted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(merchant_id) REFERENCES merchant_profile (id),
    FOREIGN KEY(category_id) REFERENCES product_category (id),
    FOREIGN KEY(reviewed_by) REFERENCES user_account (id)
);

CREATE INDEX ix_product_spu_category_id ON product_spu (category_id);
CREATE INDEX ix_product_spu_merchant_id ON product_spu (merchant_id);
CREATE INDEX ix_product_spu_name ON product_spu (name);
CREATE INDEX ix_product_spu_origin_place ON product_spu (origin_place);
CREATE INDEX ix_product_spu_status ON product_spu (status);
CREATE INDEX ix_product_spu_deleted_at ON product_spu (deleted_at);

CREATE TABLE product_sku (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    spu_id BIGINT NOT NULL,
    spec_name VARCHAR(128) NOT NULL,
    spec_attrs_json JSON,
    unit VARCHAR(32) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    original_price NUMERIC(12, 2),
    stock_available INTEGER NOT NULL DEFAULT 0,
    stock_locked INTEGER NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_product_sku_price_nonnegative CHECK (price >= 0),
    CONSTRAINT ck_product_sku_stock_available_nonnegative CHECK (stock_available >= 0),
    CONSTRAINT ck_product_sku_stock_locked_nonnegative CHECK (stock_locked >= 0),
    FOREIGN KEY(spu_id) REFERENCES product_spu (id)
);

CREATE INDEX ix_product_sku_spu_id ON product_sku (spu_id);

CREATE TABLE product_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    spu_id BIGINT NOT NULL,
    sku_id BIGINT,
    image_url VARCHAR(512) NOT NULL,
    is_cover BOOLEAN NOT NULL DEFAULT false,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(spu_id) REFERENCES product_spu (id),
    FOREIGN KEY(sku_id) REFERENCES product_sku (id)
);

CREATE INDEX ix_product_image_sku_id ON product_image (sku_id);
CREATE INDEX ix_product_image_spu_id ON product_image (spu_id);

CREATE TABLE product_traceability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    spu_id BIGINT NOT NULL,
    trace_code VARCHAR(128) NOT NULL,
    farm_name VARCHAR(128),
    harvest_date DATE,
    inspection_result VARCHAR(128),
    cold_chain_info VARCHAR(255),
    trace_steps_json JSON,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_traceability_spu_id UNIQUE (spu_id),
    FOREIGN KEY(spu_id) REFERENCES product_spu (id)
);

CREATE INDEX ix_product_traceability_spu_id ON product_traceability (spu_id);
CREATE UNIQUE INDEX ix_product_traceability_trace_code ON product_traceability (trace_code);

CREATE TABLE cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    buyer_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (buyer_id),
    FOREIGN KEY(buyer_id) REFERENCES user_account (id)
);

CREATE TABLE cart_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    selected BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(cart_id) REFERENCES cart (id),
    FOREIGN KEY(sku_id) REFERENCES product_sku (id)
);

CREATE INDEX ix_cart_item_cart_id ON cart_item (cart_id);
CREATE INDEX ix_cart_item_sku_id ON cart_item (sku_id);

CREATE TABLE checkout_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_no VARCHAR(64) NOT NULL,
    buyer_id BIGINT NOT NULL,
    status paymentstatus_enum NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    freight_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    payable_amount NUMERIC(12, 2) NOT NULL,
    receiver_snapshot_json JSON NOT NULL,
    payment_expires_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() + interval '20 minutes'),
    paid_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    expired_at TIMESTAMP WITH TIME ZONE,
    idempotency_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_checkout_payment_buyer_idempotency_key UNIQUE (buyer_id, idempotency_key),
    FOREIGN KEY(buyer_id) REFERENCES user_account (id)
);

CREATE INDEX ix_checkout_payment_buyer_id ON checkout_payment (buyer_id);
CREATE INDEX ix_checkout_payment_idempotency_key ON checkout_payment (idempotency_key);
CREATE UNIQUE INDEX ix_checkout_payment_payment_no ON checkout_payment (payment_no);
CREATE INDEX ix_checkout_payment_status ON checkout_payment (status);

CREATE TABLE purchase_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_no VARCHAR(64) NOT NULL,
    payment_id BIGINT,
    buyer_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    status orderstatus_enum NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    freight_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    payable_amount NUMERIC(12, 2) NOT NULL,
    receiver_snapshot_json JSON NOT NULL,
    expected_delivery_at TIMESTAMP WITH TIME ZONE,
    payment_expires_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() + interval '20 minutes'),
    paid_at TIMESTAMP WITH TIME ZONE,
    is_shipped BOOLEAN NOT NULL DEFAULT FALSE,
    shipped_at TIMESTAMP WITH TIME ZONE,
    idempotency_key VARCHAR(128),
    checkout_idempotency_key VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_order_buyer_idempotency_key UNIQUE (buyer_id, idempotency_key),
    CONSTRAINT uq_order_buyer_seller_checkout_key UNIQUE (buyer_id, seller_id, checkout_idempotency_key),
    FOREIGN KEY(payment_id) REFERENCES checkout_payment (id),
    FOREIGN KEY(buyer_id) REFERENCES user_account (id),
    FOREIGN KEY(seller_id) REFERENCES merchant_profile (id)
);

CREATE INDEX ix_purchase_order_buyer_id ON purchase_order (buyer_id);
CREATE INDEX ix_purchase_order_checkout_idempotency_key ON purchase_order (checkout_idempotency_key);
CREATE INDEX ix_purchase_order_idempotency_key ON purchase_order (idempotency_key);
CREATE UNIQUE INDEX ix_purchase_order_order_no ON purchase_order (order_no);
CREATE INDEX ix_purchase_order_payment_id ON purchase_order (payment_id);
CREATE INDEX ix_purchase_order_seller_id ON purchase_order (seller_id);
CREATE INDEX ix_purchase_order_status ON purchase_order (status);

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id BIGINT NOT NULL,
    spu_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    product_name_snapshot VARCHAR(128) NOT NULL,
    spec_name_snapshot VARCHAR(128) NOT NULL,
    cover_image_url_snapshot VARCHAR(512),
    unit_price NUMERIC(12, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(order_id) REFERENCES purchase_order (id),
    FOREIGN KEY(spu_id) REFERENCES product_spu (id),
    FOREIGN KEY(sku_id) REFERENCES product_sku (id)
);

CREATE INDEX ix_order_item_order_id ON order_item (order_id);
CREATE INDEX ix_order_item_sku_id ON order_item (sku_id);
CREATE INDEX ix_order_item_spu_id ON order_item (spu_id);

CREATE TABLE product_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    spu_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    content TEXT,
    images_json JSON,
    seller_reply TEXT,
    status reviewstatus_enum NOT NULL DEFAULT 'visible'::reviewstatus_enum,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_product_review_order_item_id UNIQUE (order_item_id),
    FOREIGN KEY(user_id) REFERENCES user_account (id),
    FOREIGN KEY(order_item_id) REFERENCES order_item (id),
    FOREIGN KEY(spu_id) REFERENCES product_spu (id),
    FOREIGN KEY(sku_id) REFERENCES product_sku (id)
);

CREATE INDEX ix_product_review_order_item_id ON product_review (order_item_id);
CREATE INDEX ix_product_review_sku_id ON product_review (sku_id);
CREATE INDEX ix_product_review_spu_id ON product_review (spu_id);
CREATE INDEX ix_product_review_status ON product_review (status);
CREATE INDEX ix_product_review_user_id ON product_review (user_id);

CREATE TABLE refund_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id BIGINT NOT NULL,
    order_item_id BIGINT,
    buyer_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    status refundstatus_enum NOT NULL,
    reason VARCHAR(255) NOT NULL,
    description TEXT,
    amount NUMERIC(12, 2) NOT NULL,
    evidence_images_json JSON,
    admin_note TEXT,
    seller_deadline_at TIMESTAMP WITH TIME ZONE,
    seller_handled_at TIMESTAMP WITH TIME ZONE,
    seller_note TEXT,
    seller_handler_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(order_id) REFERENCES purchase_order (id),
    FOREIGN KEY(order_item_id) REFERENCES order_item (id),
    FOREIGN KEY(buyer_id) REFERENCES user_account (id),
    FOREIGN KEY(seller_id) REFERENCES merchant_profile (id),
    FOREIGN KEY(seller_handler_id) REFERENCES user_account (id)
);

CREATE INDEX ix_refund_application_buyer_id ON refund_application (buyer_id);
CREATE INDEX ix_refund_application_order_id ON refund_application (order_id);
CREATE INDEX ix_refund_application_order_item_id ON refund_application (order_item_id);
CREATE INDEX ix_refund_application_seller_id ON refund_application (seller_id);
CREATE INDEX ix_refund_application_seller_deadline_at ON refund_application (seller_deadline_at);
CREATE INDEX ix_refund_application_status ON refund_application (status);

CREATE TABLE refund_dispute (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    refund_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    buyer_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    initiator_id BIGINT NOT NULL,
    initiator_role userrole_enum NOT NULL,
    status disputestatus_enum NOT NULL DEFAULT 'pending'::disputestatus_enum,
    reason VARCHAR(255) NOT NULL,
    description TEXT,
    evidence_images_json JSON,
    resolution_note TEXT,
    resolved_by BIGINT,
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_refund_dispute_refund_id UNIQUE (refund_id),
    FOREIGN KEY(refund_id) REFERENCES refund_application (id),
    FOREIGN KEY(order_id) REFERENCES purchase_order (id),
    FOREIGN KEY(buyer_id) REFERENCES user_account (id),
    FOREIGN KEY(seller_id) REFERENCES merchant_profile (id),
    FOREIGN KEY(initiator_id) REFERENCES user_account (id),
    FOREIGN KEY(resolved_by) REFERENCES user_account (id)
);

CREATE INDEX ix_refund_dispute_buyer_id ON refund_dispute (buyer_id);
CREATE INDEX ix_refund_dispute_initiator_id ON refund_dispute (initiator_id);
CREATE INDEX ix_refund_dispute_initiator_role ON refund_dispute (initiator_role);
CREATE INDEX ix_refund_dispute_order_id ON refund_dispute (order_id);
CREATE INDEX ix_refund_dispute_refund_id ON refund_dispute (refund_id);
CREATE INDEX ix_refund_dispute_seller_id ON refund_dispute (seller_id);
CREATE INDEX ix_refund_dispute_status ON refund_dispute (status);

CREATE TABLE order_status_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id BIGINT NOT NULL,
    from_status orderstatus_enum,
    to_status orderstatus_enum NOT NULL,
    operator_id BIGINT,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(order_id) REFERENCES purchase_order (id),
    FOREIGN KEY(operator_id) REFERENCES user_account (id)
);

CREATE INDEX ix_order_status_log_order_id ON order_status_log (order_id);
CREATE INDEX ix_order_status_log_to_status ON order_status_log (to_status);

CREATE TABLE wallet_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    available_balance NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    frozen_balance NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    version INTEGER NOT NULL DEFAULT 0,
    status walletstatus_enum NOT NULL DEFAULT 'active'::walletstatus_enum,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_wallet_available_nonnegative CHECK (available_balance >= 0),
    CONSTRAINT ck_wallet_frozen_nonnegative CHECK (frozen_balance >= 0),
    FOREIGN KEY(user_id) REFERENCES user_account (id)
);

CREATE INDEX ix_wallet_account_status ON wallet_account (status);
CREATE UNIQUE INDEX ix_wallet_account_user_id ON wallet_account (user_id);

CREATE TABLE wallet_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    wallet_account_id BIGINT NOT NULL,
    biz_type walletbiztype_enum NOT NULL,
    direction ledgerdirection_enum NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    before_available_balance NUMERIC(12, 2) NOT NULL,
    after_available_balance NUMERIC(12, 2) NOT NULL,
    before_frozen_balance NUMERIC(12, 2) NOT NULL,
    after_frozen_balance NUMERIC(12, 2) NOT NULL,
    reference_type VARCHAR(64) NOT NULL,
    reference_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_wallet_ledger_business_reference UNIQUE (wallet_account_id, biz_type, reference_type, reference_id),
    FOREIGN KEY(wallet_account_id) REFERENCES wallet_account (id)
);

CREATE INDEX ix_wallet_ledger_biz_type ON wallet_ledger (biz_type);
CREATE INDEX ix_wallet_ledger_reference_id ON wallet_ledger (reference_id);
CREATE INDEX ix_wallet_ledger_reference_type ON wallet_ledger (reference_type);
CREATE INDEX ix_wallet_ledger_wallet_account_id ON wallet_ledger (wallet_account_id);

CREATE TABLE ai_chat_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    buyer_id BIGINT,
    title VARCHAR(128),
    state_json JSON,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(buyer_id) REFERENCES user_account (id)
);

CREATE INDEX ix_ai_chat_session_buyer_id ON ai_chat_session (buyer_id);

CREATE TABLE ai_chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id BIGINT NOT NULL,
    role aimessagerole_enum NOT NULL,
    content TEXT NOT NULL,
    payload_json JSON,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(session_id) REFERENCES ai_chat_session (id)
);

CREATE INDEX ix_ai_chat_message_role ON ai_chat_message (role);
CREATE INDEX ix_ai_chat_message_session_id ON ai_chat_message (session_id);
